version: 1.2
workflows:
  - name: PerformPopulationPCA
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/PerformPopulationPCA.wdl
  - name: ScoringImputedDataset
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/ScoringPart.wdl
  - name: TrainAncestryAdjustmentModel
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/TrainAncestryAdjustmentModel.wdl
